sudo: required

matrix:
  include:
  - env: GHCVER=7.10.3
  - env: GHCVER=8.0.2
  - env: GHCVER=8.2.1
  - env: GHCVER=8.4.1
  - env: GHCVER=head
  - os: osx

script:
- export HLINT_ARGUMENTS=src
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh

deploy:
  provider: releases
  api_key:
    secure: ""
  file_glob: true
  file:  travis-release/*
  skip_cleanup: true
  on:
    tags: true
